const std = @import("std");
const plugin = @import("protobuf_plugin");

const FileDescriptorProto = @typeInfo(@TypeOf(@as(plugin.CodeGeneratorRequest, undefined).proto_file.items)).pointer.child;
const ServiceDescriptorProto = @typeInfo(@TypeOf(@as(FileDescriptorProto, undefined).service.items)).pointer.child;
const MethodDescriptorProto = @typeInfo(@TypeOf(@as(ServiceDescriptorProto, undefined).method.items)).pointer.child;

pub fn generate(
    allocator: std.mem.Allocator,
    request: plugin.CodeGeneratorRequest,
    response: *plugin.CodeGeneratorResponse,
) !void {
    if (request.parameter) |parameter| {
        if (parameter.len != 0) {
            response.@"error" = try std.fmt.allocPrint(
                allocator,
                "unsupported generator parameter: {s}",
                .{parameter},
            );
            return;
        }
    }

    var files: std.StringHashMap(*const FileDescriptorProto) = .init(allocator);
    defer files.deinit();
    for (request.proto_file.items) |*file| {
        const name = file.name orelse continue;
        try files.put(name, file);
    }

    for (request.file_to_generate.items) |name| {
        const file = files.get(name) orelse return error.MissingFileDescriptor;
        try appendFile(allocator, file, response);
    }
}

fn appendFile(
    allocator: std.mem.Allocator,
    file: *const FileDescriptorProto,
    response: *plugin.CodeGeneratorResponse,
) !void {
    const source_name = file.name orelse return error.MissingFileName;
    if (!std.mem.endsWith(u8, source_name, ".proto")) return error.InvalidProtoFileName;
    const stem = source_name[0 .. source_name.len - ".proto".len];
    const header_name = try std.fmt.allocPrint(allocator, "{s}.grpc.pb.h", .{stem});
    errdefer allocator.free(header_name);
    const source_output_name = try std.fmt.allocPrint(allocator, "{s}.grpc.pb.cc", .{stem});
    errdefer allocator.free(source_output_name);

    const header = try renderHeader(allocator, file, stem, header_name);
    errdefer allocator.free(header);
    const source = try renderSource(allocator, file, header_name);
    errdefer allocator.free(source);

    try response.file.append(allocator, .{ .name = header_name, .content = header });
    errdefer _ = response.file.pop();
    try response.file.append(allocator, .{ .name = source_output_name, .content = source });
}

fn renderHeader(
    allocator: std.mem.Allocator,
    file: *const FileDescriptorProto,
    stem: []const u8,
    header_name: []const u8,
) ![]u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("// Generated by protoc-gen-grpc_lite_cpp. DO NOT EDIT.\n");
    try writer.writeAll("#ifndef ");
    try writeHeaderGuard(writer, header_name);
    try writer.writeAll("\n#define ");
    try writeHeaderGuard(writer, header_name);
    try writer.print(
        "\n\n#include \"{s}.pb.h\"\n\n#include <grpcpp/grpcpp.h>\n#include <grpcpp/impl/client_unary_call.h>\n\n#include <memory>\n\n",
        .{stem},
    );
    try openNamespaces(writer, file.package orelse "");

    for (file.service.items) |service| {
        if (!hasUnaryMethod(service)) continue;
        try renderServiceDeclaration(writer, file.package orelse "", service);
    }

    try closeNamespaces(writer, file.package orelse "");
    try writer.writeAll("\n#endif  // ");
    try writeHeaderGuard(writer, header_name);
    try writer.writeByte('\n');
    return output.toOwnedSlice();
}

fn renderServiceDeclaration(
    writer: *std.Io.Writer,
    package: []const u8,
    service: ServiceDescriptorProto,
) !void {
    const service_name = service.name orelse return error.MissingServiceName;
    try writer.writeAll("class ");
    try writeIdentifier(writer, service_name);
    try writer.writeAll(" final {\n public:\n  static constexpr const char* service_full_name() { return \"");
    if (package.len != 0) try writer.print("{s}.", .{package});
    try writer.writeAll(service_name);
    try writer.writeAll("\"; }\n\n  class StubInterface {\n   public:\n    virtual ~StubInterface() = default;\n");
    for (service.method.items) |method| {
        if (isStreaming(method)) continue;
        try writeMethodDeclaration(writer, method, true);
    }
    try writer.writeAll("  };\n\n  class Stub final : public StubInterface {\n   public:\n    Stub(std::shared_ptr<::grpc::ChannelInterface> channel,\n         const ::grpc::StubOptions& options);\n");
    for (service.method.items) |method| {
        if (isStreaming(method)) continue;
        try writeMethodDeclaration(writer, method, false);
    }
    try writer.writeAll("\n   private:\n    std::shared_ptr<::grpc::ChannelInterface> channel_;\n  };\n\n  static std::unique_ptr<Stub> NewStub(\n      const std::shared_ptr<::grpc::ChannelInterface>& channel,\n      const ::grpc::StubOptions& options = ::grpc::StubOptions());\n};\n\n");
}

fn writeMethodDeclaration(
    writer: *std.Io.Writer,
    method: MethodDescriptorProto,
    pure_virtual: bool,
) !void {
    const name = method.name orelse return error.MissingMethodName;
    const input = method.input_type orelse return error.MissingInputType;
    const output = method.output_type orelse return error.MissingOutputType;
    try writer.writeAll("    virtual ::grpc::Status ");
    try writeIdentifier(writer, name);
    try writer.writeAll("(\n        ::grpc::ClientContext* context,\n        const ");
    try writeCppType(writer, input);
    try writer.writeAll("& request,\n        ");
    try writeCppType(writer, output);
    try writer.writeAll("* response)");
    if (pure_virtual) {
        try writer.writeAll(" = 0;\n");
    } else {
        try writer.writeAll(" override;\n");
    }
}

fn renderSource(
    allocator: std.mem.Allocator,
    file: *const FileDescriptorProto,
    header_name: []const u8,
) ![]u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;
    try writer.print(
        "// Generated by protoc-gen-grpc_lite_cpp. DO NOT EDIT.\n#include \"{s}\"\n\n#include <utility>\n\n",
        .{header_name},
    );
    try openNamespaces(writer, file.package orelse "");
    const package = file.package orelse "";
    for (file.service.items) |service| {
        if (!hasUnaryMethod(service)) continue;
        try renderServiceDefinition(writer, package, service);
    }
    try closeNamespaces(writer, package);
    return output.toOwnedSlice();
}

fn renderServiceDefinition(
    writer: *std.Io.Writer,
    package: []const u8,
    service: ServiceDescriptorProto,
) !void {
    const service_name = service.name orelse return error.MissingServiceName;
    try writeIdentifier(writer, service_name);
    try writer.writeAll("::Stub::Stub(std::shared_ptr<::grpc::ChannelInterface> channel,\n                  const ::grpc::StubOptions& options)\n    : channel_(std::move(channel)) {\n  (void)options;\n}\n\n");

    for (service.method.items) |method| {
        if (isStreaming(method)) continue;
        const method_name = method.name orelse return error.MissingMethodName;
        const input = method.input_type orelse return error.MissingInputType;
        const output = method.output_type orelse return error.MissingOutputType;
        try writer.writeAll("::grpc::Status ");
        try writeIdentifier(writer, service_name);
        try writer.writeAll("::Stub::");
        try writeIdentifier(writer, method_name);
        try writer.writeAll("(\n    ::grpc::ClientContext* context, const ");
        try writeCppType(writer, input);
        try writer.writeAll("& request,\n    ");
        try writeCppType(writer, output);
        try writer.writeAll("* response) {\n  static const ::grpc::internal::RpcMethod method(\"");
        try writer.writeByte('/');
        if (package.len != 0) try writer.print("{s}.", .{package});
        try writer.print("{s}/{s}\");\n  return ::grpc::internal::BlockingUnaryCall(\n      channel_.get(), method, context, request, response);\n}}\n\n", .{ service_name, method_name });
    }

    try writer.writeAll("std::unique_ptr<");
    try writeIdentifier(writer, service_name);
    try writer.writeAll("::Stub> ");
    try writeIdentifier(writer, service_name);
    try writer.writeAll("::NewStub(\n    const std::shared_ptr<::grpc::ChannelInterface>& channel,\n    const ::grpc::StubOptions& options) {\n  return std::unique_ptr<Stub>(new Stub(channel, options));\n}\n\n");
}

fn isStreaming(method: MethodDescriptorProto) bool {
    return (method.client_streaming orelse false) or (method.server_streaming orelse false);
}

fn hasUnaryMethod(service: ServiceDescriptorProto) bool {
    for (service.method.items) |method| if (!isStreaming(method)) return true;
    return false;
}

fn openNamespaces(writer: *std.Io.Writer, package: []const u8) !void {
    var components = std.mem.splitScalar(u8, package, '.');
    while (components.next()) |component| {
        if (component.len == 0) continue;
        try writer.writeAll("namespace ");
        try writeIdentifier(writer, component);
        try writer.writeAll(" {\n");
    }
    if (package.len != 0) try writer.writeByte('\n');
}

fn closeNamespaces(writer: *std.Io.Writer, package: []const u8) !void {
    var count: usize = 0;
    var components = std.mem.splitScalar(u8, package, '.');
    while (components.next()) |component| if (component.len != 0) {
        count += 1;
    };
    if (count != 0) try writer.writeByte('\n');
    while (count != 0) : (count -= 1) try writer.writeAll("}  // namespace\n");
}

fn writeCppType(writer: *std.Io.Writer, proto_type: []const u8) !void {
    try writer.writeAll("::");
    const name = if (proto_type.len != 0 and proto_type[0] == '.') proto_type[1..] else proto_type;
    var components = std.mem.splitScalar(u8, name, '.');
    var first = true;
    while (components.next()) |component| {
        if (!first) try writer.writeAll("::");
        try writeIdentifier(writer, component);
        first = false;
    }
}

fn writeHeaderGuard(writer: *std.Io.Writer, name: []const u8) !void {
    for (name) |character| {
        if (std.ascii.isAlphanumeric(character)) {
            try writer.writeByte(std.ascii.toUpper(character));
        } else {
            try writer.writeByte('_');
        }
    }
    try writer.writeByte('_');
}

fn writeIdentifier(writer: *std.Io.Writer, identifier: []const u8) !void {
    try writer.writeAll(identifier);
    if (isCppKeyword(identifier)) try writer.writeByte('_');
}

fn isCppKeyword(identifier: []const u8) bool {
    const keywords = [_][]const u8{
        "alignas",     "alignof",   "and",              "and_eq",       "asm",      "auto",         "bitand",    "bitor",    "bool",     "break",
        "case",        "catch",     "char",             "char8_t",      "char16_t", "char32_t",     "class",     "compl",    "concept",  "const",
        "consteval",   "constexpr", "constinit",        "const_cast",   "continue", "co_await",     "co_return", "co_yield", "decltype", "default",
        "delete",      "do",        "double",           "dynamic_cast", "else",     "enum",         "explicit",  "export",   "extern",   "false",
        "float",       "for",       "friend",           "goto",         "if",       "inline",       "int",       "long",     "mutable",  "namespace",
        "new",         "noexcept",  "not",              "not_eq",       "nullptr",  "operator",     "or",        "or_eq",    "private",  "protected",
        "public",      "register",  "reinterpret_cast", "requires",     "return",   "short",        "signed",    "sizeof",   "static",   "static_assert",
        "static_cast", "struct",    "switch",           "template",     "this",     "thread_local", "throw",     "true",     "try",      "typedef",
        "typeid",      "typename",  "union",            "unsigned",     "using",    "virtual",      "void",      "volatile", "wchar_t",  "while",
        "xor",         "xor_eq",
    };
    for (keywords) |keyword| if (std.mem.eql(u8, identifier, keyword)) return true;
    return false;
}

test "generates unary glue and skips streaming methods" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const allocator = arena_state.allocator();
    var request: plugin.CodeGeneratorRequest = .{};
    try request.file_to_generate.append(allocator, "demo/echo.proto");
    var file: FileDescriptorProto = .{ .name = "demo/echo.proto", .package = "demo" };
    var service: ServiceDescriptorProto = .{ .name = "EchoService" };
    try service.method.append(allocator, .{
        .name = "Echo",
        .input_type = ".demo.EchoRequest",
        .output_type = ".demo.EchoReply",
    });
    try service.method.append(allocator, .{
        .name = "Chat",
        .input_type = ".demo.EchoRequest",
        .output_type = ".demo.EchoReply",
        .client_streaming = true,
        .server_streaming = true,
    });
    try file.service.append(allocator, service);
    try request.proto_file.append(allocator, file);

    var response: plugin.CodeGeneratorResponse = .{};
    try generate(allocator, request, &response);
    try std.testing.expectEqual(@as(usize, 2), response.file.items.len);
    try std.testing.expectEqualStrings("demo/echo.grpc.pb.h", response.file.items[0].name.?);
    try std.testing.expect(std.mem.indexOf(u8, response.file.items[0].content.?, "virtual ::grpc::Status Echo(") != null);
    try std.testing.expect(std.mem.indexOf(u8, response.file.items[0].content.?, "return \"demo.EchoService\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, response.file.items[0].content.?, "Chat") == null);
    try std.testing.expect(std.mem.indexOf(u8, response.file.items[1].content.?, "/demo.EchoService/Echo") != null);
}

test "escapes C++20 keywords" {
    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();
    try writeIdentifier(&output.writer, "concept");
    try std.testing.expectEqualStrings("concept_", output.written());
    output.clearRetainingCapacity();
    try writeIdentifier(&output.writer, "mutable");
    try std.testing.expectEqualStrings("mutable_", output.written());
}

test "rejects unsupported parameters" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const allocator = arena_state.allocator();
    const request: plugin.CodeGeneratorRequest = .{ .parameter = "unknown=true" };
    var response: plugin.CodeGeneratorResponse = .{};
    try generate(allocator, request, &response);
    try std.testing.expectEqualStrings("unsupported generator parameter: unknown=true", response.@"error".?);
}
